swagger: '2.0'
info:
  title: joegatt.net API
  description: "Fetch notes, citations and bibliography"
  version: '3.0.0'
host: joegatt.net
schemes:
  - http
produces:
  - application/json
paths:
  /tags.json:
    get:
      summary: Tags
      description: Returns tags and counts.
      parameters:
        - name: blurb
          in: query
          description: "Return blurbs for referenced objeccts if set to 'true'."
          required: false
          type: string
      tags:
        - Tags
      responses:
        200:
          description: An array of tags.
          schema:
            type: array
            items:
              $ref: '#/definitions/Tags'
  /tags/{slug}.json:
    get:
      summary: Tags
      description: Returns a tag and blurbs for the objects it references.
      parameters:
        - name: blurb
          in: query
          description: "Return blurbs for referenced objects if set to 'true'."
          required: false
          type: string
      tags:
        - Texts
      responses:
        200:
          description: An array of texts.
          schema:
            type: array
            items:
              $ref: '#/definitions/Texts'
  /texts.json:
    get:
      summary: Texts
      description: Returns texts and metadata on joegatt.net.
      parameters:
        - name: p
          in: query
          description: Page number.
          required: false
          type: string
        - name: extended
          in: query
          description: Return expanded views.
          required: false
          type: string
        - name: blurb
          in: query
          description: "Return blurbs for texts if set to 'true'."
          required: false
          type: string
        - name: body
          in: query
          description: "Return text body. Options are 'raw', 'simple' and 'html'."
          required: false
          type: string
      tags:
        - Texts
      responses:
        200:
          description: An array of texts.
          schema:
            type: array
            items:
              $ref: '#/definitions/Texts'
  /texts/{id}.json:
    get:
      summary: Text
      description: Returns a text and its metadata.
      parameters:
        - name: id
          in: path
          description: Unique identifier of the requested text.
          required: true
          type: string
        - name: extended
          in: query
          description: Return expanded view.
          required: false
          type: string
        - name: blurb
          in: query
          description: Return blurbs for text if set to 'true'.
          required: false
          type: string
        - name: body
          in: query
          description: Return text body. Options are 'raw', 'simple' and 'html'.
          required: false
          type: string
      tags:
        - Texts
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                items:
                  $ref: '#/definitions/Text'
definitions:
  Tag:
    type: object
    properties:
      slug:
        type: string
        description: Parameterised version of tag name.
      canonical_url:
        type: string
        description: Canonical url for this tag.
      name:
        type: string
        description: Titlecased version of this tag.
      count:
        type: integer
        description: Number of references for this tag.
  Tags:
    type: object
    properties:
      count:
        type: integer
        description: Number of tags available.
      references_count:
        type: integer
        description: Number of notes, citations, books and links referenced by this tag.
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
  Texts:
    type: object
    properties:
      count:
        type: integer
        description: Number of texts available in all pages.
      paginates_per:
        type: integer
        description: Maximum number of texts in a single pages.
      page_number:
        type: integer
        description: Page number of the array in texts.
      total_word_count:
        type: integer
        description: Word count for all texts in all pages (calculated at 5.5 characters per word).
      texts:
        type: array
        items:
          $ref: '#/definitions/Text'
  Text:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific text.
      canonical_url:
        type: string
        description: Canonical url for this text.
      main_title:
        type: string
        description: Main title for this text.
      subtitle:
        type: string
        description: Subtitle of this text (if present).
      blurb:
        type: string
        description: A short blurb for this text.
      introduction:
        type: string
        description: Subtitle of this text (if present).
      feature_title:
        type: string
        description: Slug for feature group of this text (if preset).
      feature_subtitle:
        type: string
        description: Slug for feature item of this text (if preset).
      lang:
        type: string
        description: Unicode for language of this text.
      author:
        type: string
        description: The name of the author of this text.
      licence:
        type: string
        description: Url pointing to text of licence under which this text is available.
      created_at:
        type: string
        description: Date when this text was created.
      updated_at:
        type: string
        description: Date when this text was last modified.
      version:
        type: string
        description: Version number of this text.
      word_count:
        type: string
        description: Word length of this text (at 5.5 characters per word).
      instructions:
        type: string
        description: Comma-separated list of hints on displaying this text.
      tags:
        type: string
        description: Comma-separated list of tags.
      blurb_title:
        type: string
        description: Title suitable for a blurb in a listing.
      blurb_body:
        type: string
        description: Body content suitable for a blurb in a listing.
      body:
        type: string
        description: Body content of the note, in either raw, simple or html format.
