defaults: &defaults
  advanced:
    admin_email: CHANGE_ME@CHANGE_ME
    admin_name: CHANGE_ME
    allowed_html_attributes: href src alt cite
    allowed_html_tags: a blockquote del ins li ol ul img strong table tbody td tr
    always_reset_on_create: true
    attempts: 3
    author: CHANGE_ME
    average_word_length: 5.5
    blurb_length: 400
    blurb_omission: ...
    books_index_per_page: 30
    books_section: false
    cache_buster: 5
    citation_blurb_length: 230
    citation_max_length: 9999
    citations_index_per_page: 10
    comments_native_or_disqus_or_none: native
    contact_email: CHANGE_ME@CHANGE_ME
    detect_language_sample_length: 250
    disqus_shortname: CHANGE_ME_OPTIONAL
    facebook_app_id: CHANGE_ME_OPTIONAL
    google_analytics_key: 'UA-16898823-3'
    instructions_citation: __QUOTE __CITATION
    instructions_link: __CLIP __LINK
    instructions_collate: __COLLATE
    instructions_default: __TRI
    instructions_feature: __FEATURE
    instructions_feature_first: __FEATURE_FIRST
    instructions_feature_last: __FEATURE_LAST
    instructions_hide: __HIDE
    instructions_hide_image: __HIDE_IMAGE __NO_IMAGE
    instructions_hide_introduction: __HIDE_INTRO __NO_INTRO
    instructions_hide_versions: __HIDE_VERSION_LIST __NO_VERSION_LIST
    instructions_ignore: __IGNORE __HOLD
    instructions_interlinear: __INTERLINEAR
    instructions_map: __MAP
    instructions_parallel: __PARALLEL
    instructions_promote: __PROMOTE
    instructions_required: __PUBLISH
    instructions_reset: __RESET
    instructions_unlist: __UNLIST __NO_LIST __SECTION __SOURCE
    instructions_unversion: __UNVERSION __NO_VERSION
    links_index_per_page: 100
    links_section: true
    locale: en
    notes_index_per_page: 10
    share_native_or_iframes_or_none: native
    tags_index_per_page: 120
    tags_index_style: false
    tags_minimum: 2
    title_length: 40
    truncate_after_regexp: --30--
    twitter_user_name: nembrotcom
    version_gap_distance: 100
    version_gap_minutes: 60
    versions: true
    web_channels: facebook.com/joegattnet twitter.com/joegattnet github.com/joegattnet plus.google.com/+JoegattNet youtube.com/joegatt0net vimeo.com/joegattnet soundcloud.com/joegattnet joegattnet.tumblr.com

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
