defaults: &defaults
  advanced:
    allowed_html_attributes: href src alt cite
    allowed_html_tags: a blockquote del ins li ol ul img strong
    always_reset_on_create: true
    attempts: 3
    author: Joe Gatt
    average_word_length: 5.5
    blurb_length: 400
    blurb_omission: ...
    books_index_per_page: 30
    citation_blurb_length: 230
    citation_max_length: 9999
    citations_index_per_page: 10
    comments_native_or_disqus_or_none: native
    comments_from_email: joe@joegatt.net
    contact_email: joe@joegatt.net
    contact_name: Joe
    detect_language_sample_length: 250
    disqus_shortname: joegattnet
    instructions_citation: __QUOTE __CITATION
    instructions_collate: __COLLATE
    instructions_default: __TRI
    instructions_feature: __FEATURE
    instructions_feature_first: __FEATURE_FIRST
    instructions_feature_last: __FEATURE_LAST
    instructions_hide: __HIDE
    instructions_hide_image: __HIDE_IMAGE __NO_IMAGE
    instructions_hide_introduction: __HIDE_INTRO __NO_INTRO
    instructions_hide_versions: __HIDE_VERSION_LIST __NO_VERSION_LIST
    instructions_ignore: __IGNORE __HOLD
    instructions_interlinear: __INTERLINEAR
    instructions_map: __MAP
    instructions_parallel: __PARALLEL
    instructions_promote: __PROMOTE
    instructions_required: __PUBLISH
    instructions_reset: __RESET
    instructions_unlist: __UNLIST __NO_LIST __SECTION __SOURCE
    instructions_unversion: __UNVERSION __NO_VERSION
    links_index_per_page: 60
    links_section: false
    locale: en
    monitoring_email: joe@joegatt.net
    monitoring_name: Joe
    notes_index_per_page: 10
    share_native_or_iframes_or_none: native
    tags_index_per_page: 120
    tags_index_style: false
    tags_minimum: 2
    title: Nembrot
    title_length: 40
    truncate_after_regexp: --30--
    twitter_user_name: nembrotcom
    version_gap_distance: 100
    version_gap_minutes: 60
    versions: true
    web_channels: facebook.com/joegattnet twitter.com/joegattnet github.com/joegattnet googleplus.com/joegattnet youtube.com/joegattnet vimeo.com/joegattnet soundcloud.com/joegattnet spotify.com/joegattnet

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
