defaults: &defaults
  database_encryption_key: CHANGEME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  secret_token: CHANGEME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  mailer:
    user_name: CHANGEME
    password: CHANGEME
  auth:
    evernote:
      consumer_key: CHANGEME
      consumer_secret: CHANGEME
    detect_language:
      api_key: CHANGEME
    world_cat:
      api_key: CHANGEME
    isbndb:
      api_key: CHANGEME

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
