defaults: &defaults
  database_encryption_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  secret_key_base: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  devise_secret_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  mailer:
    address: CHANGE_ME
    port: CHANGE_ME
    domain: CHANGE_ME
    user_name: CHANGE_ME
    password: CHANGE_ME
  auth:
    detect_language:
      key: optional
    evernote:
      username: CHANGE_ME
      key: CHANGE_ME
      secret: CHANGE_ME
    facebook:
      key: optional
      secret: optional
    github:
      key: optional
      secret: optional
    gplus:
      key: optional
      secret: optional
    isbndb:
      key: optional
    linkedin:
      key: optional
      secret: optional
    twitter:
      key: CHANGE_ME
      secret: CHANGE_ME
      pantography:
        key: CHANGE_ME
        secret: CHANGE_ME
        access_token: CHANGE_ME
        access_secret: CHANGE_ME
    world_cat:
      key: optional

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
