defaults: &defaults
  database_encryption_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  secret_key_base: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  devise_secret_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  mailer:
    user_name: CHANGE_ME
    password: CHANGE_ME
  auth:
    evernote:
      consumer_key: CHANGE_ME
      consumer_secret: CHANGE_ME
    detect_language:
      api_key: CHANGE_ME
    world_cat:
      api_key: CHANGE_ME
    isbndb:
      api_key: CHANGE_ME
    twitter:
      pantography:
        consumer_key: CHANGE_ME
        consumer_secret: CHANGE_ME
        access_token: CHANGE_ME
        access_secret: CHANGE_ME

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
