defaults: &defaults
  database_encryption_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  secret_key_base: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  devise_secret_key: CHANGE_ME_TO_AT_LEAST_30_RANDOM_ALPHANUMERIC_CHARACTERS_80_OR_SO_IS_BETTER
  mailer:
    user_name: CHANGE_ME
    password: CHANGE_ME
  auth:
    detect_language:
      key: CHANGE_ME
    evernote:
      key: CHANGE_ME
      secret: CHANGE_ME
    facebook:
      key: CHANGE_ME
      secret: CHANGE_ME
    github:
      key: CHANGE_ME
      secret: CHANGE_ME
    gplus:
      key: CHANGE_ME
      secret: CHANGE_ME
    isbndb:
      key: CHANGE_ME
    linkedin:
      key: CHANGE_ME
      secret: CHANGE_ME 
    twitter:
      key: CHANGE_ME
      secret: CHANGE_ME
    world_cat:
      key: CHANGE_ME

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
