defaults: &defaults
  style:
    background_color: '#fff'
    body_font: Georgia
    body_font_citation_color: '#000'
    body_font_citation_family: DejaVuSansCondensed, Arial, Helvetica, sans-serif
    body_font_citation_size: 15px
    body_font_color: '#000'
    body_font_family: Georgia, serif
    body_font_size: 18px
    body_font_variant: regular
    border_color: '#ccc'
    caption_color: '#454545'
    citation_style: default
    column_width: 60
    container_style: magic
    count_color: '#900'
    css_for_instructions: __FX_POL __SECTION __ENUMERATE
    delete_font_color: '#000'
    error_background_color: '#ff4545'
    evernote_color: '#61b737'
    facebook_color: '#3b5998'
    font_color: '#000'
    font_family: DejaVuSansCondensed, Arial, Helvetica, sans-serif
    font_size: 15px
    force_double_quotes: true
    furniture_color: '#666'
    github_color: '#201f1f'
    gplus_color: '#dd4b39'
    grid_padding: 0
    gutter_width: 30
    headline_font: DejaVuSansCondensed
    headline_font_color: '#090'
    headline_font_family: DejaVuSansCondensed, Arial, Helvetica, sans-serif
    headline_font_size: 36px
    headline_font_variant: condensed_book
    hyper_conform: false
    images_cinema_aspect_x: 27
    images_cinema_aspect_y: 10
    images_cinema_width: 12
    images_effects:
    images_expanded_width: 1400
    images_gravity: 0
    images_name_length: 30
    images_min_width: 799
    images_snap: 1
    images_standard_aspect_x: 16
    images_standard_aspect_y: 9
    images_standard_width: 8
    images_thumbnail_aspect_x: 16
    images_thumbnail_aspect_y: 9
    images_thumbnail_width: 3
    insert_background_color: '#ffff45'
    invalid_background_color: '#ff0'
    line_height: 30
    link_color: '#000'
    link_hover_color: '#009'
    link_visited_color: '#000'
    linkedin_color: '#1c87bd'
    map_background_color: '#ccc'
    map_font_color: '#333'
    monospace_font: DejaVuMonoBook
    monospace_font_family: DejaVuMonoBook, monospace
    monospace_font_variant: mono_book
    note_images_number: 1
    off_color: '#999'
    promotions_footer: 5
    promotions_home_columns: 3
    promotions_home_lines: 7
    promotions_home_rows: 2
    promotions_home_show_image?: false
    qr_code_image_size: 150
    row_hover_color: '#ff0'
    secondary_color: '#333'
    selected_background_color: '#ff0'
    selected_font_color: '#000'
    small_font_size: 13px
    static_url_color: '#090'
    success_background_color: '#45ff45'
    total_columns: 12
    total_width: 100%
    twitter_color: '#00acee'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
